### ISSUE TITLE
Unable to load model on iOS

### ISSUE THREAD

**Issue by alexyaroshuk** [xuegao-tzx/Fllama#2]
Device: iPhone 8
iOS: 16.6.1

Tested the same build, same model, on Android - no issues there
Did a debug build to add logs to confirm file existance in the dir - not the path issue, file exists

Logs:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(505, Failed to load the model, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      MethodChannelFCllama.initContext (package:fcllama/fllama_method_channel.dart:49)
<asynchronous suspension>
#3      HomeVM.initModel.<anonymous closure> (package:fcllama_example/vm/HomeVM.dart:123)
<asynchronous suspension>

**Comment by xuegao-tzx** [comment]
What version of Xcode are you using?

**Comment by xuegao-tzx** [comment]
I can initialize and use it normally on an iPhone 15 Pro Max using Xcode version 15.4 (15F31d) and iOS 18.2 (22C5142a)

**Comment by alexyaroshuk** [comment]
Yes, upon working with llama.rn I can confirm that this is a hardware issue. It seems iPhone 8 is not supported. Thanks
